[package]
name = "boop-gtk"
version = "0.1.0"
authors = ["ben"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sourceview = "0.8.0"
glib = "0.9.3"
gdk = "0.12.1"
rust-embed = "5.5.1"
rusty_v8 = "0.5.1"
libc = "0.2.71"

[dependencies.gtk]
version = "0.8.1"
features = ["v3_16"]

[dependencies.gio]
version = "0.8.1"
features = ["v2_44"]