name: boop-gtk
title: Boop-GTK
version: '1.1.0'
icon: snap/gui/boop-gtk.png
summary: Port of IvanMathy's Boop to GTK, a scriptable scratchpad for developers.
description: |
  Paste text, transform it (with user extendible javascipt), move on. Stop pasting sensitive infomation into sketchy sites to format JSON, compute a hash, etc.

base: core18
confinement: strict

build-packages:
  - gcc
  - libc6-dev

parts:
  boop-gtk:
    plugin: rust
    source: https://github.com/mrbenshef/Boop-GTK.git
    source-tag: v1.1.0

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: uk.co.mrbenshef.Boop-GTK

apps:
  boop-gtk:
    command: bin/boop-gtk
    extensions: [gnome-3-34]
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - unity7
    slots:
    - dbus-daemon
    common-id: uk.co.mrbenshef.Boop-GTK